### ISSUE TITLE
ERROR: EXCEPTION Thrown (PythonToCppException)

### ISSUE THREAD

**Issue by djggy** [b-jesch/script.program.fritzact#1]
Hi,

i have install fritzact on LibreElec 9.2.0 and have the following error:
===========================
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <type 'exceptions.IndexError'>
 Error Contents: string index out of range
 Traceback (most recent call last):
 File "/storage/.kodi/addons/script.program.fritzact/default.py", line 347, in <module>
 fritz = FritzBox()
 File "/storage/.kodi/addons/script.program.fritzact/default.py", line 141, in __init__
    self.getSettings()
 File "/storage/.kodi/addons/script.program.fritzact/default.py", line 190, in getSettings
    self.__fbpasswd = crypter('fbPasswd', 'fb_key', 'fb_token')
 File "/storage/.kodi/addons/script.program.fritzact/resources/lib/tools.py", line 27, in crypter
   if len(_key) > 2: return "".join([chr(ord(_token[i]) ^ ord(_key[i])) for i in range(int(_key[-2:]))])
   IndexError: string index out of range
   -->End of Python script error report<--
=================================

**Comment by b-jesch** [comment]
Don't use special chars in passwords, i.e no 'Ä, Ö, Ü or ß'. Make your settings, store/close the settings and run the script outside of the settings dialog (don't start from within settings). The exception should disappear.
Don't wonder if your password is replaced later by "`*`", this is a result of the decrypter function. Kodi stores passwords unencrypted. As this is a security hole, the decrypter replace the passwords by "`*`" and use a token and a dynamic key instead.

**Comment by djggy** [comment]
I had a dot in my password. I think that was the problem.
Thanks for your tip and support.
